### ISSUE TITLE
Authentication by Email is case sensitive

### ISSUE THREAD

**Issue by joyponader** [ether/pad#146]
When I register with my email in lower cases, an upper case first letter when loggin in makes the Login fail.

**Comment by sesam** [comment]
So we'd like to lowercase all email user inputs. Typically find them with:
fgrep -r request.params.email src/*

**Comment by sesam** [comment]
Hopefully the "80%" fix in https://github.com/ether/pad/commit/15f8474031ca0866973b74d8bd4af656a87fadb2  doesn't break things for anyone? I noticed afterwards that it went right up on ether/pad - scream at me if I broke something, ok?

**Comment by redhog** [comment]
Did this fix (already merged, hay, ask someone else to review and pull next time, k?) fix the problem? Should we close this issue?

**Comment by sesam** [comment]
There may be some places that do not convert to lowercase on both sides of the comparison.

Option A) My idea is to add code to make sure that any new passwords are lowercased, and also make sure any passwords that are stored in the DB are lowercased. The last part should probably be done with a DB migration of the type that is checked when etherpad is starting up.
Option B) The corollary option is to revert 15f8474031ca0866973b74d8bd4af656a87fadb2 and schedule this for a later milestone. 
Option C) Revert and lowercase the passwords in the DB + lowercase all newly created passwords. If hashing of passwords is added then we would need to do exactly the same lowercasing-operation before hashing, in order to be fully case-insensitive.

Maybe johannesponander can say if this is important enough to have in a half-baked state in 1.1.1
