### ISSUE TITLE
login/logout/authentication

### ISSUE THREAD

**Issue by holtzermann17** [ether/pad#16]
It would be good to provide some form of bloc-wide authentication to prevent spamming/spoofing.

**Comment by penSecIT** [comment]
Authentification is default with pro setups. For a installation wide password protection I would recommend to proxy it with apache/nginx

**Comment by holtzermann17** [comment]
So, we should close this issue?

**Comment by johnuren1980** [comment]
No, please don't. I have installed Etherpad for a large-ish organisation and they love it, except I can never get pro accounts working because the IT admins can't do the DNS wildcard. Authentication is important because we require an auditable trail of who wrote and said what. If someone does do this, could they make it work with LDAP please. Thanks

**Comment by redhog** [comment]
This should really just be merged into the ticket to get pro pads/team pads work without sub-domains.

As for LDAP, there's been some work on various different auth schemes for pro pads...

**Comment by johnuren1980** [comment]
If this has been discussed, I'm happy to merge.

**Comment by redhog** [comment]
Oh, you have a branch? I can't see it at github.com/ether/pad/network, did you fork from github.com/ether/pad ?

**Comment by johnuren1980** [comment]
apologies, You are confusing me with someone who can code to the appropriate standard. I meant merge the bugs/requests. Quote: "This should really just be merged into the ticket to get pro pads/team pads work without sub-domains."

**Comment by redhog** [comment]
Ah :) No worries :)
