### ISSUE TITLE
Extract text from pads

### ISSUE THREAD

**Issue by anirudhr** [ether/pad#209]
A PHP function to extract the plaintext of the latest revision from a pad. Will help in resolving issue 187, MediaWiki plug-in for Etherpad.

**Comment by sesam** [comment]
Since etherpad is programmed mostly in javascript, your wanted PHP-function would have to integrate with etherpad either by making a HTTP call to the read-only view (easy, but will totally bog down your PHP serving application) or create some background program thread to do the work for you and deliver the contents asynchronously to your PHP application, perhaps by making a HTTP POST to your PHP application, or by injecting the data into a database on the PHP server you're using.

Closing this issue since there's nothing that even needs to / can be done in the etherpad source code to help you.
