### ISSUE TITLE
Export charset broken

### ISSUE THREAD

**Issue by redhog** [ether/pad#212]
Hi,
I have that nasty misbehavious with etherpad not exporting cleanly French text with various accentuated characters to word of odf formats. I tried the two fixes mentioned here, but this did not help. Curious that the pdf produced by the export is clean...
Can someone lead me to a fix ?
Robert Herzog

**Comment by Erode** [comment]
I applied : 
- https://github.com/gaqzi/pad/commit/6cbfae42410933f70d20f50d99dd66dea2787b88
- https://github.com/gaqzi/pad/commit/b42345eef0f38bb0a582241a5480d07f3188f747
- https://github.com/ether/pad/commit/b42345eef0f38bb0a582241a5480d07f3188f747 

And it works fine on exports with version 1.1 on Ubuntu 9.10 and OpenOffice 1:3.1.1-5ubuntu1.3.

I still have 3 accent issues : 
- JS alerts (for import/export for instance)
- mails encoding (for account creation for instance)
- default text in pads

Would love any hints on this.

**Comment by ilpssun** [comment]
I can confirm the problem for our installation of EtherPad 1.1 on CentOS with OpenOffice.org 3.1.1.  Both Word (DOC) and OpenOffice (ODT) export have a broken character encoding, not representing unicode characters, such as curly quotes, correctly.  Surprisingly, it works well for PDF export.  I haven't tried any of the patches, yet, because we need the system up and running for the time being.
