### ISSUE TITLE
etherpad not support rtl languages (like Hebrew and Arabic)

### ISSUE THREAD

**Issue by amiad** [ether/pad#243]
The text in etherpad align to left but Hebrew and Arabic written from right to left and them need to align to right.
I think that need to add button align text to right and set direction rtl.

**Comment by tomer** [comment]
In Google Docs it is possible to set the document direction from the document properties dialog, and this might be good feature in Etherpad. 

As for the paragraph level, there should be support for setting per-paragraph direction in addition to globally setting the document direction.

**Comment by amire80** [comment]
It is possible to use Ctrl-Shift-X in Firefox to switch the whole editing field to be right-to-left, but it only works for editing and it is not saved. It must be possible to set the directionality for every paragraph.

Another problem is that the cursor moves in the wrong direction when the arrow keys are pressed. On other websites the arrow keys work correctly, even if the website is not specifically adapted to right-to-left languages.

**Comment by mushon** [comment]
I'm not a geek but I am assuming this issue should not be rocket science and would make Etherpad so much more relevant for RTL users. Any chance of getting a coder on it? Maybe using an existing language detection lib or something? A quick search found this: http://plugins.jquery.com/project/direction-detector

**Comment by sesam** [comment]
@amire80, "On other websites the arrow keys work correctly, even if the website is not specifically adapted to right-to-left languages." are those websites using contentEditable?
Because I'm afraid that a regular textarea (like what you use to write comments on Github and on 99,99% of websites) are well-developed, while the "contentEditable" feature is not well developed, and has several known bugs and limitations. And contentEditable is what etherpad uses. So I'm afraid that bugs should preferably be solved in the web browsers, and browser-specific workarounds can be added to etherpad to support older/buggier browsers when it is at all possible.
Since contentEditable is a browser built-in, it might not be possible to "hook" the cursor buttons and switch them around from javascript and it might require a browser plugin or similar, but any experimentation is of course very welcome.

**Comment by amire80** [comment]
I think that GMail in rich text mode uses contentEditable (though i might be wrong) and RTL support there is better than in EtherPad. Not perfect, but better.

**Comment by slim** [comment]
solved in my tree: https://github.com/slim/etherpad-lite/commit/7f38efbaff5604b27948f0e43edb4d91858533f6

it's a little bit hackish but it works. At least in chrome.

@mushon Y U NO ASK ME ;)

**Comment by mushon** [comment]
Awesome!
I should've asked you… :)

BTW, I just came across ICE from the NYTimes, might be another solution for a similar need:
http://nytimes.github.com/ice/demo/

How are you doing?  

## 

Mushon Zer-Aviv
Mushon.com (http://Mushon.com) | Shual.com (http://Shual.com) | @Mushon (http://twitter.com/mushon)

**Comment by JohnMcLear** [comment]
Oh this should have been closed months ago.   See the Right to Left plugin https://npmjs.org/package/ep_right_to_left
