### ISSUE TITLE
etherpad does a server error when sending a forgotten password reminder

### ISSUE THREAD

**Issue by eseyman** [ether/pad#299]
When I got to the "Recover lost password" page (on /ep/account/forgot-password), enter my password and hit the "Send Email" button, I get a page that says:

"Oops! A server error occured. It's been logged.

Please email support@etherpad.com if this persists."

The exception logs gives me a rather long trace. I've put it up online here:
http://people.parinux.org/~seyman/etherpad.log

**Comment by sesam** [comment]
The interesting part of the trace is probably this form near the top:
    at java.lang.Integer.parseInt(Integer.java:514)
    at net.appjet.oui.config$.extractHostAndPort(config.scala:117)
    at net.appjet.oui.config$.smtpServerHost(config.scala:189)
    at net.appjet.ajstdlib.email$.sendEmail(ajstdlib.scala:220)

and without checking the source, it appears that etherpad either only supports IP-numbers for the mail host (and not a hostname) or something else.

Does it work to send password reminders if you run your etherpad with 127.0.0.1 instead of the "smtp.intranet" or whatever you're currently using?

**Comment by eseyman** [comment]
I tried using 127.0.0.1 without any luck (see http://people.parinux.org/~seyman/etherpad.1.log).

Seeing the expression extractHostAndPort in your reply, I then tried using 127.0.0.1:25 in the configuration file and the email is now sent.

I'll admit I find the parsing a bit too sensitive for my taste but my problem is solved so feel free to close the ticket.
