### ISSUE TITLE
Contact info at http://etherpad.org/contact/ broken

### ISSUE THREAD

**Issue by AlainKnaff** [ether/pad#303]
Yesterday I had tried to email the etherpad team about a more general issue, and attempted to use the contact address at http://etherpad.org/contact/ ("Email" link near top right of the page)

contact@etherpad.org

However, after sending a mail to this address, it bounced.
Apparently, the MX records configured in DNS are faulty:

> host -t mx etherpad.org
> etherpad.org mail is handled by 10 secure.primaryt.co.uk.etherpad.org.
> etherpad.org mail is handled by 20 duck.mclear.co.uk.etherpad.org.

Etherpad.org is (errnoneously?) appended to both records, this can happen when forgetting to include a trailing dot for the MX record in the DNS zone file. If this dot is not there, DNS software automatically appends current domain (etherpad.org) even though secure.primaryt.co.uk and duck.mclear.co.uk are already complete host names.

So I tried to get around this by setting up a manual route to the target mail server in my /etc/mail/mailertable .

However, even that did not work.
On primaryt.co.uk, I got "The email address that you entered couldn't be found", and on duck.mclear.co.uk I got "contact@etherpad.org: Relay access denied"

===> so none of the 2 MX'es configured seem to know about contact@etherpad.org , even without the typo in the DNS zone file.

Moreover, the etherpad.org zone file has a SOA from January 18th this year... and apparently since then nobody seems to have noticed that mails intended for contact don't come in.

===> so wouldn't it be useful to replace the mail address on http://etherpad.org/contact/ with one that works (... and is read), or remove that page altogether

**Comment by JohnMcLear** [comment]
Egil?!?!

I have put 3 or 4 requests in with Egil, my impression is that they were sorted.

The emails come to me btw.

You can reach me at john@mclear.co.uk

-----Original Message-----
From: AlainKnaff [mailto:reply@reply.github.com]
Sent: 12 November 2011 19:08
To: John McLear
Subject: [pad] Contact info at http://etherpad.org/contact/ broken (#303)

Yesterday I had tried to email the etherpad team about a more general issue, and attempted to use the contact address at http://etherpad.org/contact/ ("Email" link near top right of the page)

contact@etherpad.org

However, after sending a mail to this address, it bounced.
Apparently, the MX records configured in DNS are faulty:

> host -t mx etherpad.org
> etherpad.org mail is handled by 10 secure.primaryt.co.uk.etherpad.org.
> etherpad.org mail is handled by 20 duck.mclear.co.uk.etherpad.org.

Etherpad.org is (errnoneously?) appended to both records, this can happen when forgetting to include a trailing dot for the MX record in the DNS zone file. If this dot is not there, DNS software automatically appends current domain (etherpad.org) even though secure.primaryt.co.uk and duck.mclear.co.uk are already complete host names.

So I tried to get around this by setting up a manual route to the target mail server in my /etc/mail/mailertable .

However, even that did not work.
On primaryt.co.uk, I got "The email address that you entered couldn't be found", and on duck.mclear.co.uk I got "contact@etherpad.org: Relay access denied"

===> so none of the 2 MX'es configured seem to know about contact@etherpad.org , even without the typo in the DNS zone file.

Moreover, the etherpad.org zone file has a SOA from January 18th this year... and apparently since then nobody seems to have noticed that mails intended for contact don't come in.

===> so wouldn't it be useful to replace the mail address on http://etherpad.org/contact/ with one that works (... and is read), or remove that page altogether

---

Reply to this email directly or view it on GitHub:
https://github.com/ether/pad/issues/303
This email and its attachments may be confidential and are intended solely for the use of the individual to whom it is addressed. Any views or opinions expressed are solely those of the author and do not necessarily represent those of the organisation from which this email originated. If you are not the intended recipient of this email and its attachments, you must take no action based upon them, nor must you copy or show them to anyone. Please contact the sender if you believe you have received this email in error. This email was sent by School Email - Safe Webmail and Hosted Email for Schools;/p>

**Comment by AlainKnaff** [comment]
Interesting... so did you get my e-mails from yesterday morning (original attempts) and this morning (repeated attempts cycling through all the MXes and other variations...)

**Comment by JohnMcLear** [comment]
No.  I got one email from you today I think

-----Original Message-----
