### ISSUE TITLE
Etherpad lite and Mysql

### ISSUE THREAD

**Issue by bartounet16** [ether/pad#317]
Hello
etherpad workks well with dirty db but not with mysql
 message 2012-05-09 13:40:56.942] [ERROR] console - Error: Access denied for user 'root'@'localhost' (using password: NO)

 although mysql is set well because i acced it whith myql -p without no problem

I don't understand...

I am on Ubuntu 10.04 64 bits

**Comment by JohnMcLear** [comment]
Your issue is with connectivity to MySQL.

Try

mysql -uroot -hlocalhost

-----Original Message-----
From: bartounet16 [mailto:reply@reply.github.com]
Sent: 09 May 2012 14:10
To: John McLear
Subject: [pad] Etherpad lite and Mysql (#317)

Hello
etherpad workks well with dirty db but not with mysql  message 2012-05-09 13:40:56.942] [ERROR] console - Error: Access denied for user 'root'@'localhost' (using password: NO)

 although mysql is set well because i acced it whith myql -p without no problem

I don't understand...

I am on Ubuntu 10.04 64 bits

---

Reply to this email directly or view it on GitHub:
https://github.com/ether/pad/issues/317
This email and its attachments may be confidential and are intended solely for the use of the individual to whom it is addressed. Any views or opinions expressed are solely those of the author and do not necessarily represent those of the organisation from which this email originated. If you are not the intended recipient of this email and its attachments, you must take no action based upon them, nor must you copy or show them to anyone. Please contact the sender if you believe you have received this email in error. This email was sent by School Email - Safe Webmail and Hosted Email for Schools

**Comment by redhog** [comment]
You need to specify host "localhost" not empty string "", as mysql
connects using unix sockets if you select empty string as host. Over
unix sockets it does not care about password, but uses ident auth by
default.
