### ISSUE TITLE
better font support

### ISSUE THREAD

**Issue by holtzermann17** [ether/pad#40]
we should have more than one font.

**Comment by JohnMcLear** [comment]
afaik there is a service that has implemented this.  I can't remember which..  maybe ietherpad?

**Comment by holtzermann17** [comment]
could be fun to hook in to the Google Font API, http://code.google.com/webfonts

**Comment by JohnMcLear** [comment]
That is a great idea!  Do you happen to know if the Google Font API has a list API that lists the available fonts and their corresponding css & font name?  If not we should request that.

**Comment by redhog** [comment]
what about just using css @fontface + allow any URL to be used to specify font, but with a drop down of URL:s listed in any public pad (searchable by tags), that ends in .ttf? You could even integrate with file upload, so that you could upload a ttf font and use it.

However, all solutions to this problem, really all, depend on modern browsers with @fontface support; if not, you're restricted to what's in the individual users' OS :(

**Comment by assel** [comment]
I would be happy just to be able to switch from proportional to a noneproportional font... maybe this feature is easier to implement than adding support for ttf?

**Comment by redhog** [comment]
Assel: That already exists, under Pad options :)

**Comment by redhog** [comment]
This is being developed by @xmbms
