### ISSUE TITLE
better cut and paste

### ISSUE THREAD

**Issue by holtzermann17** [ether/pad#6]
This needs browser-specific debugging.

Currently w/ Firefox, C-x/C-v stuff doesn't work, nor C-k/C-y using KeySnail, but cut/paste from the Edit menu does work; another KeySnail interoperability bug is that C-e, C-b and the like set the mark before cursor movement begins).

On Safari, Cmd-X/Cmd-V work like a charm (and maintaining author attribution colors).

**Comment by redhog** [comment]
This might even be operating system specific :/

**Comment by laughinghan** [comment]
I imagine only Firefox would give OS-specific hell

**Comment by zeigerpuppy** [comment]
It would be nice if copying/pasting had the option of maintaining exiting authorship too.

**Comment by redhog** [comment]
This _should_ be possible by using/reusing the special css classes etherpad uses to mark up authors. However, this is rather dangerous: It would allow anyone to produce custom-authored text, to pervert history if you like. It would also pose the problem that you could have a text that contains authors that are not available in the current pad (e.g. because the text comes from another pad).

**Comment by theoryshaw** [comment]
Hi Egil, I pine for this option daily.  Wonder if it could be an option the pad author could turn on/off?

**Comment by theoryshaw** [comment]
couldn't those css classes be pad-specific?...to prevent cross-pad copy/paste.

**Comment by holtzermann17** [comment]
@zeigerpuppy: note that if you copy and paste a piece of text that has multiple lines and multiple authors, colors are preserved.

**Comment by theoryshaw** [comment]
@holtzermann17 good to know, thanks!
