### ISSUE TITLE
remove cruft

### ISSUE THREAD

**Issue by holtzermann17** [ether/pad#73]
The current package includes various peripheral junk (like personal photos of the original Appjet developers, other unused images, and so on) which should probably be removed, both because they seem generally useless, and for copyright reasons.  The same goes for any unused or unuseful code, of course.

**Comment by holtzermann17** [comment]
One strategy would be to make a UML style diagram of the project and zap anything that doesn't fit into the diagram properly.

**Comment by cjb** [comment]
> for copyright reasons

There aren't any copyright issues; the code was released publicly, intentionally.  Your point still stands, though.

**Comment by redhog** [comment]
Personal photos might have non-copyright issues in many jurisdictions....

**Comment by cjb** [comment]
I still think that's a non-issue.  Google made this release; if their lawyers are happy with it, I see no reason that we shouldn't be.

**Comment by redhog** [comment]
Hehe, true :) But we don't want the junk there anyway :P

**Comment by holtzermann17** [comment]
Marking this as high priority, because it is really a sort of meta-issue for the whole code cleanup project.  Anyone who wants to clean up the code should start by getting rid of junk we don't need.

**Comment by sesam** [comment]
Note that I think we've once or twice removed code that turned out to be needed; i.e. checkin comments of the style "removed X" ... "readded X". There are some pieces we don't test much or at all; including the admin pages and subpages, pro-functionality, and more. We might need to figure out some guide or standard on how to identify if a file is used by the project or not. Is searching (grep:ing) thep whole project for the filename excluding extension good enough? (I.e. searching for "ace-old" instead of "ace-old.js")

(D'oh - it seems I managed to close this issue by mistake - and I can't reopen it?)

**Comment by holtzermann17** [comment]
Note that various mentions of "etherpad.com" in text blocks probably count as cruft these days.  E.g there's lots of this stuff in pro.

**Comment by sesam** [comment]
There are nowadays very few mentions of etherpad.com left. Apart from the store and billing stuff which probably nobody uses, there are also something in metrics/metrics.js needing the current website's hostname (request.host?) and some email addresses @etherpad.com or @appjet.com which may work, but should really be fixed too.

List of suspects:

egrep -lre "(appjet|etherpad).com[^a-z]" *
billing/team_billing.js
control/statscontrol.js
control/pad/pad_control.js
control/pro_beta_control.js
control/aboutcontrol.js
control/pro/admin/team_billing_control.js
control/historycontrol.js
control/store/eepnet_checkout_control.js
control/global_pro_account_control.js
licensing.js
metrics/metrics.js
pad/padutils.js
pro/pro_accounts.js
quotas.js
store/checkout.js
store/eepnet_checkout.js
store/eepnet_trial.js
