### ISSUE TITLE
Bouncy sidebar bug: Choose Full window, disable sidebar, notice bounciness (IE7)

### ISSUE THREAD

**Issue by sesam** [ether/pad#90]
With sidebar off, full window on, if you're in a fairly active document with some few long wrapping text lines, you'll notice how the sidebar pops back in each time someone joins or leaves the pad.
It seems this also occurs if someone writes something in the chat box.

(Reproducible on IE7 on 1.0.1 and on original google OSS release. This might be a "feature" originally, but it has to be modified or removed)

**Comment by JohnMcLear** [comment]
Same as : http://github.com/ether/pad/issues#issue/24 ?

**Comment by holtzermann17** [comment]
Very similar to #131 but #24 is actually quite different (that one's a feature request, not a bug report).  This issue is IE-specific and the other one is iframe-related so I suspect both are just related to the longstanding "iframe" issue.  However, if you look at the details of this bug, it's actually slightly different from the behaviour noted in #131, so let's leave it open.
